# build only master branch and version tags
branches:
  only:
  - master
  - /^\d*\.\d*\.\d*$/

sudo: required

services:
- docker

language: cpp
dist: xenial
os: linux

addons:
  apt:
    sources:
      - sourceline: 'deb http://dl.bintray.com/igagis/ubuntu xenial main'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x379CE192D401AB61'
    update: true
    packages:
    - binfmt-support
    - qemu-user-static
    - myci

matrix:
  include:
    - name: macosx
      os: osx
      compiler: clang
      osx_image: xcode8.3
    - name: ios
      os: osx
      compiler: clang
      osx_image: xcode8.3
    - name: android
      language: android
      android:
        components:
          - platform-tools
          - tools
          - build-tools-25.0.2
          - android-25
#          - sys-img-armeabi-v7a-android-22
          - extra-android-m2repository

env:
  global:
  # Encrypted MYCI_BINTRAY_API_KEY for publishing to bintray.
  - secure: "HqIV2oUl1Fpvs5cHQdCaOutdO1VtETnlIEdwInjdETZeDl4G05VROgSWMKoAOKWus3r8hJcZLz4bpGS8Jn9BOZgUh1KyE5/IEhG4o1GutLNtvvkHhcnggPGrG/2Lujnqj+QKNlAoGSPFtX/fRV1ZCab1z4QNXLs0PCP4LpkkcAqXKrcPtESQLbAxQYiNaqyN8ZWg9ob9acHLep71V9OpIcuGGzPO6DW2vhWfnMo4rp715Kmcbxj8lVxYiAenXZp333Zx+c3l7H7jLgqozNWXzrT7If6pQHIQ3KlGJFCtVXwH1qROKxkr0AwkYtNUmNBPFZCh8N61mKyrlRYkqQY+C1vWvOpqaC+/9ASGq9LfJdfz3Op8JqPIlnG70rlZZ7Av5FWiGIU2/lPrQ8ile7BBn77QxaeMRr81L+kce62GyQDenWQ9lP0jTScN6sCz3fFz5rJkVGK7ioScEt6yVS/vNzYAiq9a/41WwBPuDan4UTr2lFxr0cTOuqmugkNdAqQcca5JlX/ImsbxdMyDBKF9fO9imlWrFgN0QCVciADDDrTs7QqoVafZwPDC0cP9U0fPiuNpzOwANL2F2+FWhYdLrHH5Dg5WObpUOtk1cWRERuxgiDGHiOQoa4ucTyfJdf4BzOTqSxI1ndRNlEEU/+BiJHysIx2FKGLDqQrNIIBlQbk="
  # Encrypted MYCI_GIT_ACCESS_TOKEN for publishing to homebrew-tap.
  - secure: "QrMC5xtPy61Y0L3HVQoPJJ0/oGHV/mGnLmS5VlL+dyKHlTzwuLeIbUOc6yv3GyREAAH4WJXULROvxzecaKI25l1ywGReQvOv3lQ0/MFsVIYhmdMYbfgY6T1TgkBMEIZS5TFe8UzIjga4kTbjnEPQERxz/yhecl5f3/2RMX6bzgG39m79yB7LtK5cJXmX9rc8913IkAfpey9rW4L4V8adJvAo1OBlYg+dDAj7KQ/4fNtn03dffwoGV3HBuBmICeKGTomIrEbW8gtA0NFkJ43QKBIcexc4MHTYxb0vJ+ZTPDZiFTVhGMQ3VafaidLzXL5jP+YUfV+64Dd88zeo3Qpv7DHWMzrJ7EHSwK0PkwD4rlKdsbY3a1fcc+QlfXAX6HNVTMpE+f+VOXw0FGWSzRkUTmj8rfkV2DL0bZOqroqYYcBsqQlO0bIzwxu3ZuiFfnO5CYXBVLxwnnrVtYzJVyzWJwgQ2AzoS0YMfJE6SrKVevYZUMcTn8H7h10i/1VyhQyx/koLDwd1pVv/6BWDFCLpAlrHrRy+/EebthG2pJhW2fxG0fU8hM0U7dXJSG7i5NMOlj/JtEegP/nvgQOAgFocjY+fC7NNM2tETArSIBbt5qchZTX+XC2/u8YB7LydhBmphL6SlIiIjq+C8jRT8oV/XijcBhDU1+zZ52+BPyFO4tI="
  - MYCI_GIT_USERNAME=igagis
  - USE_ANDROID_NDK_VERSION=15c
  - PACKAGE_NAME=kolme
  matrix:
  - OS_REL=xenial OS=ubuntu DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=bionic OS=ubuntu DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=stretch OS=debian DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=stretch OS=raspbian DOCKER_IMAGE=igagis/$OS:$OS_REL PACKAGE_TYPE=deb

before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
    docker run --name ccc -v $TRAVIS_BUILD_DIR/..:/build -w /build/$(basename $TRAVIS_BUILD_DIR) -it -d $DOCKER_IMAGE bash &&
    if [ "$PACKAGE_TYPE" == "deb" ]; then
      docker exec ccc apt update &&
      docker exec ccc apt install -y dirmngr &&
      docker exec ccc bash -c "echo 'deb http://dl.bintray.com/igagis/$OS $OS_REL main' > /etc/apt/sources.list.d/igagis.list" &&
      docker exec ccc apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
      docker exec ccc apt update &&
      docker exec ccc apt install -y devscripts equivs myci &&
      myci-deb-prepare.sh;
    fi;
  fi
- if [ "$TRAVIS_JOB_NAME" == "macosx" ]; then
    rvm install ruby-2.3.3 &&
    rvm use ruby-2.3.3 &&
    
    brew update > /dev/null &&
    brew tap igagis/tap &&
    brew update > /dev/null &&
    brew install myci prorab prorab-extra libutki;
  fi
- if [ "$TRAVIS_JOB_NAME" == "ios" ]; then
    rvm install ruby-2.3.3 &&
    rvm use ruby-2.3.3 &&
    
    brew update > /dev/null &&
    brew tap igagis/tap &&
    brew update > /dev/null &&
    brew install myci &&
    
    sudo gem install cocoapods &&
    pod repo add --silent igagis https://$MYCI_GIT_USERNAME:$MYCI_GIT_ACCESS_TOKEN@github.com/igagis/cocoapods-repo.git;
  fi
# download and install android NDK
- if [ "$TRAVIS_JOB_NAME" == "android" ]; then
    export TERM=dumb &&
    curl -L https://dl.google.com/android/repository/android-ndk-r$USE_ANDROID_NDK_VERSION-linux-x86_64.zip -O &&
    unzip ./android-ndk-r$USE_ANDROID_NDK_VERSION-linux-x86_64.zip > /dev/null &&
    rm android-ndk-r$USE_ANDROID_NDK_VERSION-linux-x86_64.zip &&
    export ANDROID_NDK_HOME=`pwd`/android-ndk-r$USE_ANDROID_NDK_VERSION &&
    export LOCAL_ANDROID_NDK_HOME="$ANDROID_NDK_HOME" &&
    export LOCAL_ANDROID_NDK_HOST_PLATFORM="linux-x86_64" &&
    export PATH=$PATH:${ANDROID_NDK_HOME} &&
    env;
  fi

install:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
    docker exec ccc myci-deb-install-build-deps.sh;
  fi

script:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
    docker exec ccc dpkg-buildpackage -us -uc;
  fi
- if [ "$TRAVIS_JOB_NAME" == "macosx" ]; then
    make;
  fi
# need to reduce output from xcodebuild because log size on travis-ci is limited by 4Mb, use grep for errors and warnings
# Also, need to set pipefail to make pipe exit code nono-zero in case first command fails but second succeeds (because grep exits with 0 always)
- if [ "$TRAVIS_JOB_NAME" == "ios" ]; then
    xcodebuild -workspace ios/tests.xcworkspace -scheme tests CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
            | sed -e "s/export PATH=[^ ]*/export PATH=.../g"
            | sed -e "s/[^ ]*\/clang /clang /g"
            | sed -e "s/\(-[IWfFL]\)[^ ]*/% /g"
            | sed -e "s/-isystem [^ ]*/%/g"
            | sed -e "s/-include [^ ]*/%/g"
            | sed -e "s/-MF [^ ]*/%/g"
            | sed -e "s/--serialize-diagnostics [^ ]*/%/g"
            | sed -e "s/-o [^ ]*/%/g"
            | sed -e "s/-iquote [^ ]*/%/g"
            | sed -e "s/-isysroot [^ ]*/%/g";
  fi
- if [ "$TRAVIS_JOB_NAME" == "android" ]; then
    (cd android && ./gradlew build) &&
    myci-apply-version.sh -v `myci-deb-version.sh debian/changelog` android/*.pom.in &&
    myci-apply-version.sh -v `myci-deb-version.sh debian/changelog` android/*.aar.in --filename-only;
  fi

before_deploy:
  - myci-apply-version.sh -v `myci-deb-version.sh debian/changelog` travis_bintray_*.json.in

deploy:
- provider: script
  skip_cleanup: true
  on:
    tags: true
    condition: $PACKAGE_TYPE = deb && -z "$TRAVIS_JOB_NAME"
  script: myci-deploy-debian-bintray.sh -u igagis -r $OS -p $PACKAGE_NAME -c main -d $OS_REL $TRAVIS_BUILD_DIR/../*.deb
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_JOB_NAME = android
  file: travis_bintray_android.json
  user: igagis
  key:
    secure: "O+G/Mak4SwnlJW0+ty3zA3zTA1Ua2AT2O/zCH7Lfp+OuWeZ8ocbp6MnYHuSL7jpUc8INObrP9B3ZPQxT8bTGmN0BK+DaKnxPwqCU7Z65UtJGBWV2fgw0AYnUSe78pefzO2il0lD9sX1g10riilFApRQ8lHlnMJra/FKgZ6ohsMExHtCnFE9jdrVhEe/tY8Y5m0qySJVbVyVXwReQj441/WCeB2QsyEYu+WSx/dn4DCl2okweVrpkW3+kFn1yXQUjnZuvXkuZWc9qCYg1YIXihjoA4MGC4fVwTma6OkhDqlOCqJBEnMNBMfRI9JHaQQzg/z9jvt/k9DXeMIICbmAFnRauoXN1o7KtTRYUVc+iBP6Fd035FVhC/PBbWS4d5+QL7wvGk6j4InE2ybnG2ePF5NbDDWxDDd7l6nsshN5pWcSEWsdXf2J8X1FeHcSO16X5b+vZHiptpdLJld56ghkIGPfTNOv4wsocU6rH262XzDdUG7D/THRJDQyfCATV2aME82XVntyQlRbp9iTfBgWiccKGDkLNFl8vYhAxH1XbLV6lAOyT0ZVRhxtQroos03G8w04i4akw7ewk3YwlQx+WxmD6wmITSc1lNiFCDzps/kPMf2+02t6/pQl+coSjyWx8wRGq1Z+rrQCYNUCzu7v1N5z29knwY367Wniz9sYZR7c="
  dry-run: false
- provider: script
  skip_cleanup: true
  script: myci-deploy-homebrew.sh -t igagis/tap
  on:
    tags: true
    condition: $TRAVIS_JOB_NAME = macosx
- provider: script
  skip_cleanup: true
  script: rvm 2.3.3 do myci-deploy-cocoapods.sh -r igagis
  on:
    tags: true
    condition: $TRAVIS_JOB_NAME = ios
    