sudo: required

services:
- docker

language: cpp
dist: xenial
os: linux

git:
  autocrlf: false

addons:
  apt:
    sources:
      - sourceline: 'deb http://dl.bintray.com/igagis/ubuntu xenial main'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x379CE192D401AB61'
    update: true
    packages:
    - binfmt-support
    - qemu-user-static
    - myci
  homebrew:
    update: true
    taps:
    - igagis/tap
    packages:
    - myci


matrix:
  include:
    - name: macosx
      os: osx
      compiler: clang
      osx_image: xcode11
    - name: ios
      os: osx
      compiler: clang
      osx_image: xcode11
    - name: android
      language: android
      android:
        components:
          - platform-tools
          - tools
          - build-tools-28.0.3
          - android-28
#          - sys-img-armeabi-v7a-android-22
          - extra-android-m2repository
    - name: msys2
      os: windows

env:
  global:
  # Encrypted MYCI_BINTRAY_API_KEY for publishing to bintray.
  - secure: "HqIV2oUl1Fpvs5cHQdCaOutdO1VtETnlIEdwInjdETZeDl4G05VROgSWMKoAOKWus3r8hJcZLz4bpGS8Jn9BOZgUh1KyE5/IEhG4o1GutLNtvvkHhcnggPGrG/2Lujnqj+QKNlAoGSPFtX/fRV1ZCab1z4QNXLs0PCP4LpkkcAqXKrcPtESQLbAxQYiNaqyN8ZWg9ob9acHLep71V9OpIcuGGzPO6DW2vhWfnMo4rp715Kmcbxj8lVxYiAenXZp333Zx+c3l7H7jLgqozNWXzrT7If6pQHIQ3KlGJFCtVXwH1qROKxkr0AwkYtNUmNBPFZCh8N61mKyrlRYkqQY+C1vWvOpqaC+/9ASGq9LfJdfz3Op8JqPIlnG70rlZZ7Av5FWiGIU2/lPrQ8ile7BBn77QxaeMRr81L+kce62GyQDenWQ9lP0jTScN6sCz3fFz5rJkVGK7ioScEt6yVS/vNzYAiq9a/41WwBPuDan4UTr2lFxr0cTOuqmugkNdAqQcca5JlX/ImsbxdMyDBKF9fO9imlWrFgN0QCVciADDDrTs7QqoVafZwPDC0cP9U0fPiuNpzOwANL2F2+FWhYdLrHH5Dg5WObpUOtk1cWRERuxgiDGHiOQoa4ucTyfJdf4BzOTqSxI1ndRNlEEU/+BiJHysIx2FKGLDqQrNIIBlQbk="
  # Encrypted MYCI_GIT_ACCESS_TOKEN for publishing to homebrew-tap.
  - secure: "QrMC5xtPy61Y0L3HVQoPJJ0/oGHV/mGnLmS5VlL+dyKHlTzwuLeIbUOc6yv3GyREAAH4WJXULROvxzecaKI25l1ywGReQvOv3lQ0/MFsVIYhmdMYbfgY6T1TgkBMEIZS5TFe8UzIjga4kTbjnEPQERxz/yhecl5f3/2RMX6bzgG39m79yB7LtK5cJXmX9rc8913IkAfpey9rW4L4V8adJvAo1OBlYg+dDAj7KQ/4fNtn03dffwoGV3HBuBmICeKGTomIrEbW8gtA0NFkJ43QKBIcexc4MHTYxb0vJ+ZTPDZiFTVhGMQ3VafaidLzXL5jP+YUfV+64Dd88zeo3Qpv7DHWMzrJ7EHSwK0PkwD4rlKdsbY3a1fcc+QlfXAX6HNVTMpE+f+VOXw0FGWSzRkUTmj8rfkV2DL0bZOqroqYYcBsqQlO0bIzwxu3ZuiFfnO5CYXBVLxwnnrVtYzJVyzWJwgQ2AzoS0YMfJE6SrKVevYZUMcTn8H7h10i/1VyhQyx/koLDwd1pVv/6BWDFCLpAlrHrRy+/EebthG2pJhW2fxG0fU8hM0U7dXJSG7i5NMOlj/JtEegP/nvgQOAgFocjY+fC7NNM2tETArSIBbt5qchZTX+XC2/u8YB7LydhBmphL6SlIiIjq+C8jRT8oV/XijcBhDU1+zZ52+BPyFO4tI="
  - MYCI_GIT_USERNAME=igagis
  - PACKAGE_NAME=r4
  matrix:
  - OS_REL=xenial OS=ubuntu DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=bionic OS=ubuntu DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=stretch OS=debian DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=buster OS=debian DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=stretch OS=raspbian DOCKER_IMAGE=igagis/$OS:$OS_REL PACKAGE_TYPE=deb

before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
    docker run --name ccc -v $TRAVIS_BUILD_DIR/..:/build -w /build/$(basename $TRAVIS_BUILD_DIR) -it -d $DOCKER_IMAGE bash &&
    if [ "$PACKAGE_TYPE" == "deb" ]; then
      docker exec ccc apt update &&
      docker exec ccc apt install -y dirmngr &&
      docker exec ccc bash -c "echo 'deb http://dl.bintray.com/igagis/$OS $OS_REL main' > /etc/apt/sources.list.d/igagis.list" &&
      docker exec ccc apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
      docker exec ccc apt update &&
      docker exec ccc apt install -y devscripts equivs myci &&
      myci-deb-prepare.sh;
    fi;
  fi
- if [ "$TRAVIS_JOB_NAME" == "macosx" ]; then
    brew install prorab prorab-extra libutki;
  fi
- if [ "$TRAVIS_JOB_NAME" == "ios" ]; then
    sudo gem install cocoapods &&
    pod repo add --silent igagis https://$MYCI_GIT_USERNAME:$MYCI_GIT_ACCESS_TOKEN@github.com/igagis/cocoapods-repo.git &&
    pod install --project-directory=xcode;
  fi
- if [ "$TRAVIS_JOB_NAME" == "msys2" ]; then
    choco upgrade --no-progress -y msys2 &&
    export msys2="/c/tools/msys64/msys2_shell.cmd -defterm -no-start -msys -here -c" &&
    $msys2 "echo -e '[igagis_msys]\\nSigLevel ^= Optional TrustAll\\nServer ^= https://dl.bintray.com/igagis/msys2/msys' ^>^> /etc/pacman.conf" &&
    $msys2 "echo -e '[igagis_mingw64]\\nSigLevel ^= Optional TrustAll\\nServer ^= https://dl.bintray.com/igagis/msys2/mingw64' ^>^> /etc/pacman.conf" &&
    $msys2 "echo -e '[igagis_mingw32]\\nSigLevel ^= Optional TrustAll\\nServer ^= https://dl.bintray.com/igagis/msys2/mingw32' ^>^> /etc/pacman.conf" &&
    $msys2 "pacman -Sy --noconfirm myci mingw-w64-x86_64-toolchain mingw-w64-i686-toolchain";
  fi
- if [ "$TRAVIS_OS_NAME" == "linux" ] || [ "$TRAVIS_OS_NAME" == "osx" ]; then
    export PACKAGE_VERSION=$(myci-deb-version.sh debian/changelog);
  fi

install:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
    docker exec ccc myci-deb-install-build-deps.sh;
  fi
# Accept android SDK licenses and install android tools
- if [ "$TRAVIS_JOB_NAME" == "android" ]; then
    echo y | sdkmanager "ndk-bundle" &&
    echo y | sdkmanager "cmake;3.6.4111459";
  fi

before_script:
# - if [ "$TRAVIS_JOB_NAME" == "ios" ]; then
#     curl -L https://github.com/zackslash/Xcode-Proj-Adder/raw/master/bin/XcodeProjAdder -O &&
#     chmod +x XcodeProjAdder &&
#     (cd xcode/$PACKAGE_NAME && ../../XcodeProjAdder -XCP $PACKAGE_NAME.xcodeproj -SCSV `echo $(find ../../src -type f -name *.cpp) | sed -E -e 's/ /,/g'`)
#   fi
- if [ "$TRAVIS_JOB_NAME" == "msys2" ]; then
    $msys2 "myci-apply-version.sh -v \$^(myci-deb-version.sh debian/changelog^) msys2/PKGBUILD.in";
  fi

script:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
    docker exec ccc dpkg-buildpackage -us -uc;
  fi
- if [ "$TRAVIS_JOB_NAME" == "macosx" ]; then
    make;
  fi
- if [ "$TRAVIS_JOB_NAME" == "ios" ]; then
    xcodebuild -workspace xcode/$PACKAGE_NAME.xcworkspace -scheme $PACKAGE_NAME CONFIGURATION_BUILD_DIR=../build -configuration Release &&
    myci-create-zip-package.sh -h src -f LICENSE $PACKAGE_NAME-$PACKAGE_VERSION.zip;
  fi
- if [ "$TRAVIS_JOB_NAME" == "android" ]; then
    (cd android && ./gradlew build) &&
    myci-apply-version.sh -v $PACKAGE_VERSION android/*.pom.in &&
    myci-apply-version.sh -v $PACKAGE_VERSION android/*.aar.in --filename-only;
  fi
# running MSYS2 script from deployment provider did not work for some reason, so we do it here if the commit is a tagged one.
- if [ "$TRAVIS_JOB_NAME" == "msys2" ]; then
    $msys2 "^(cd msys2 ^&^& PKGEXT^='.pkg.tar.xz' makepkg-mingw --syncdeps --noconfirm --skipinteg^)" &&
    if [ ! -z "$TRAVIS_TAG" ]; then
      for f in $(find msys2 -name "mingw-w64-x86_64-$PACKAGE_NAME-*-any.pkg.*"); do
        $msys2 "myci-deploy-pacman-bintray.sh -u igagis -r msys2 -p mingw64 -d igagis_mingw64 $f";
      done &&
      for f in $(find msys2 -name "mingw-w64-i686-$PACKAGE_NAME-*-any.pkg.*"); do
        $msys2 "myci-deploy-pacman-bintray.sh -u igagis -r msys2 -p mingw32 -d igagis_mingw32 $f";
      done;
    fi;
  fi

before_deploy:


deploy:
- provider: script
  skip_cleanup: true
  on:
    tags: true
    condition: $PACKAGE_TYPE = deb && -z "$TRAVIS_JOB_NAME"
  script: myci-deploy-debian-bintray.sh -u igagis -r $OS -p $PACKAGE_NAME -c main -d $OS_REL $TRAVIS_BUILD_DIR/../*.deb
- provider: script
  skip_cleanup: true
  script: myci-deploy-maven-bintray.sh -u igagis -r android -d io/github/igagis -p $PACKAGE_NAME -v $PACKAGE_VERSION android/$PACKAGE_NAME-$PACKAGE_VERSION.aar
  on:
    tags: true
    condition: $TRAVIS_JOB_NAME = android
- provider: script
  skip_cleanup: true
  script: myci-deploy-homebrew.sh -t igagis/tap
  on:
    tags: true
    condition: $TRAVIS_JOB_NAME = macosx
- provider: script
  skip_cleanup: true
  script: myci-deploy-cocoapods.sh -r igagis -v $PACKAGE_VERSION -u igagis -b cocoapods -p $PACKAGE_NAME-$PACKAGE_VERSION.zip cocoapods/$PACKAGE_NAME.podspec.in
  on:
    tags: true
    condition: $TRAVIS_JOB_NAME = ios
